
spring:
  application:
    name: shopree

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    validate-on-migrate: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: ['shopree']
    table: flyway_schema_history
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    clean-disabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
